### ISSUE TITLE
SyntaxError on `cornell netid`

### ISSUE THREAD

**Issue by yuhuanq** [mrkev/cornell#4]
I get the following error when trying to use the netid functionality

```
/usr/lib/node_modules/cornell/node_modules/plant.js/Plant.js:2
let rp         = require('./request_promise')
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/cornell/bin/cornell-netid:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Any ideas?

**Comment by mrkev** [comment]
This happens if you don't have the latest version of node.js. Try installing version 5 or 6
